let start = Date.now();
const sampleData = [
    {
        "_id": "63f9c31ec3f0a7c0f1c438e9",
        "trainno": "10103",
        "type": "",
        "train_name": "MANDOVI EXPRESS",
        "distanceInKm": 765,
        "Route": [
            {
                "no": 1,
                "code": "CSMT",
                "station": "Chhatrapati Shivaji Terminus MUMBAI CST",
                "state": "",
                "arrival": "00:00",
                "departure": "07:10",
                "halt": 0,
                "day": 1,
                "distance": 0,
                "distanceFromSrc": 0
            },
            {
                "no": 2,
                "code": "DR",
                "station": "DADAR",
                "state": "",
                "arrival": "07:22",
                "departure": "07:25",
                "halt": 3,
                "day": 1,
                "distance": 9,
                "distanceFromSrc": 9
            },
            {
                "no": 3,
                "code": "TNA",
                "station": "THANE",
                "state": "",
                "arrival": "07:47",
                "departure": "07:50",
                "halt": 3,
                "day": 1,
                "distance": 25,
                "distanceFromSrc": 34
            },
            {
                "no": 4,
                "code": "DIVA",
                "station": "DIVA",
                "state": "",
                "arrival": "08:00",
                "departure": "08:01",
                "halt": 1,
                "day": 1,
                "distance": 18,
                "distanceFromSrc": 43
            },
            {
                "no": 5,
                "code": "PNVL",
                "station": "PANVEL",
                "state": "",
                "arrival": "08:25",
                "departure": "08:30",
                "halt": 5,
                "day": 1,
                "distance": 51,
                "distanceFromSrc": 69
            },
            {
                "no": 6,
                "code": "MNI",
                "station": "MANGAON",
                "state": "",
                "arrival": "10:27",
                "departure": "10:28",
                "halt": 1,
                "day": 1,
                "distance": 137,
                "distanceFromSrc": 188
            },
            {
                "no": 7,
                "code": "KHED",
                "station": "KHED",
                "state": "",
                "arrival": "11:46",
                "departure": "11:47",
                "halt": 1,
                "day": 1,
                "distance": 147,
                "distanceFromSrc": 284
            },
            {
                "no": 8,
                "code": "CHI",
                "station": "CHIPLUN",
                "state": "",
                "arrival": "12:20",
                "departure": "12:21",
                "halt": 1,
                "day": 1,
                "distance": 178,
                "distanceFromSrc": 325
            },
            {
                "no": 9,
                "code": "SGR",
                "station": "SANGMESHWAR",
                "state": "",
                "arrival": "13:25",
                "departure": "13:26",
                "halt": 1,
                "day": 1,
                "distance": 206,
                "distanceFromSrc": 384
            },
            {
                "no": 10,
                "code": "RN",
                "station": "RATNAGIRI",
                "state": "",
                "arrival": "14:10",
                "departure": "14:15",
                "halt": 5,
                "day": 1,
                "distance": 225,
                "distanceFromSrc": 431
            },
            {
                "no": 11,
                "code": "ADVI",
                "station": "ADAVALI",
                "state": "",
                "arrival": "14:51",
                "departure": "14:52",
                "halt": 1,
                "day": 1,
                "distance": 250,
                "distanceFromSrc": 475
            },
            {
                "no": 12,
                "code": "RAJP",
                "station": "RAJAPUR ROAD",
                "state": "",
                "arrival": "15:41",
                "departure": "15:42",
                "halt": 1,
                "day": 1,
                "distance": 270,
                "distanceFromSrc": 520
            },
            {
                "no": 13,
                "code": "VBW",
                "station": "VAIBHAVWADI RD",
                "state": "",
                "arrival": "16:00",
                "departure": "16:01",
                "halt": 1,
                "day": 1,
                "distance": 273,
                "distanceFromSrc": 543
            },
            {
                "no": 14,
                "code": "KKW",
                "station": "KANKAVALI",
                "state": "",
                "arrival": "16:43",
                "departure": "16:44",
                "halt": 1,
                "day": 1,
                "distance": 314,
                "distanceFromSrc": 587
            },
            {
                "no": 15,
                "code": "SNDD",
                "station": "SINDHUDURG",
                "state": "",
                "arrival": "17:09",
                "departure": "17:10",
                "halt": 1,
                "day": 1,
                "distance": 298,
                "distanceFromSrc": 612
            },
            {
                "no": 16,
                "code": "KUDL",
                "station": "KUDAL",
                "state": "",
                "arrival": "17:23",
                "departure": "17:24",
                "halt": 1,
                "day": 1,
                "distance": 328,
                "distanceFromSrc": 626
            },
            {
                "no": 17,
                "code": "SWV",
                "station": "SAWANTWADI ROAD",
                "state": "",
                "arrival": "17:51",
                "departure": "17:52",
                "halt": 1,
                "day": 1,
                "distance": 327,
                "distanceFromSrc": 655
            },
            {
                "no": 18,
                "code": "PERN",
                "station": "PERNEM",
                "state": "",
                "arrival": "18:19",
                "departure": "18:20",
                "halt": 1,
                "day": 1,
                "distance": 359,
                "distanceFromSrc": 686
            },
            {
                "no": 19,
                "code": "THVM",
                "station": "THIVIM",
                "state": "",
                "arrival": "18:34",
                "departure": "18:35",
                "halt": 1,
                "day": 1,
                "distance": 342,
                "distanceFromSrc": 701
            },
            {
                "no": 20,
                "code": "KRMI",
                "station": "KARMALI",
                "state": "",
                "arrival": "19:01",
                "departure": "19:02",
                "halt": 1,
                "day": 1,
                "distance": 383,
                "distanceFromSrc": 725
            },
            {
                "no": 21,
                "code": "VEN",
                "station": "VERNA",
                "state": "",
                "arrival": "19:11",
                "departure": "19:12",
                "halt": 1,
                "day": 1,
                "distance": 365,
                "distanceFromSrc": 748
            },
            {
                "no": 22,
                "code": "MAO",
                "station": "MADGAON",
                "state": "",
                "arrival": "20:10",
                "departure": "00:00",
                "halt": 0,
                "day": 1,
                "distance": 400,
                "distanceFromSrc": 765
            }
        ],
        "runtime": {
            "days": 0,
            "hours": 13,
            "mins": 10
        },
        "stops": 22,
        "avgSpeed": "48 km/hr",
        "seatsAvailibility": {
            "firstAc": {
                "charges_per_100km": 295,
                "total_coach": 2,
                "general_seats": 6,
                "ladies_seats": 4,
                "tatkal_seats": 2,
                "senior_citizen": 6
            },
            "secondAc": {
                "charges_per_100km": 172,
                "total_coach": 2,
                "general_seats": 48,
                "ladies_seats": 4,
                "tatkal_seats": 4,
                "senior_citizen": 8
            },
            "thirdAc": {
                "charges_per_100km": 120,
                "total_coach": 4,
                "general_seats": 50,
                "ladies_seats": 4,
                "tatkal_seats": 9,
                "senior_citizen": 9
            },
            "sleeper": {
                "charges_per_100km": 46,
                "total_coach": 9,
                "general_seats": 50,
                "ladies_seats": 4,
                "tatkal_seats": 9,
                "senior_citizen": 9
            }
        },
        "classes": "SL 3A 2A 1A",
        "schedule": "S\tM\tT\tW\tT\tF\tS",
        "return": "10104"
    },
    {
        "_id": "63f9c31ec3f0a7c0f1c438ea",
        "trainno": "10104",
        "type": "",
        "train_name": "MANDOVI EXPRESS",
        "distanceInKm": 765,
        "Route": [
            {
                "no": 1,
                "code": "MAO",
                "station": "MADGAON",
                "state": "",
                "arrival": "00:00",
                "departure": "08:30",
                "halt": 0,
                "day": 1,
                "distance": 0,
                "distanceFromSrc": 0
            },
            {
                "no": 2,
                "code": "VEN",
                "station": "VERNA",
                "state": "",
                "arrival": "08:55",
                "departure": "08:56",
                "halt": 1,
                "day": 1,
                "distance": 18,
                "distanceFromSrc": 18
            },
            {
                "no": 3,
                "code": "KRMI",
                "station": "KARMALI",
                "state": "",
                "arrival": "09:09",
                "departure": "09:10",
                "halt": 1,
                "day": 1,
                "distance": 23,
                "distanceFromSrc": 41
            },
            {
                "no": 4,
                "code": "THVM",
                "station": "THIVIM",
                "state": "",
                "arrival": "09:29",
                "departure": "09:30",
                "halt": 1,
                "day": 1,
                "distance": 42,
                "distanceFromSrc": 65
            },
            {
                "no": 5,
                "code": "PERN",
                "station": "PERNEM",
                "state": "",
                "arrival": "09:41",
                "departure": "09:42",
                "halt": 1,
                "day": 1,
                "distance": 38,
                "distanceFromSrc": 80
            },
            {
                "no": 6,
                "code": "SWV",
                "station": "SAWANTWADI ROAD",
                "state": "",
                "arrival": "10:06",
                "departure": "10:07",
                "halt": 1,
                "day": 1,
                "distance": 73,
                "distanceFromSrc": 111
            },
            {
                "no": 7,
                "code": "KUDL",
                "station": "KUDAL",
                "state": "",
                "arrival": "10:29",
                "departure": "10:30",
                "halt": 1,
                "day": 1,
                "distance": 67,
                "distanceFromSrc": 140
            },
            {
                "no": 8,
                "code": "SNDD",
                "station": "SINDHUDURG",
                "state": "",
                "arrival": "10:41",
                "departure": "10:42",
                "halt": 1,
                "day": 1,
                "distance": 87,
                "distanceFromSrc": 154
            },
            {
                "no": 9,
                "code": "KKW",
                "station": "KANKAVALI",
                "state": "",
                "arrival": "11:01",
                "departure": "11:02",
                "halt": 1,
                "day": 1,
                "distance": 92,
                "distanceFromSrc": 179
            },
            {
                "no": 10,
                "code": "VBW",
                "station": "VAIBHAVWADI RD",
                "state": "",
                "arrival": "11:31",
                "departure": "11:32",
                "halt": 1,
                "day": 1,
                "distance": 130,
                "distanceFromSrc": 222
            },
            {
                "no": 11,
                "code": "RAJP",
                "station": "RAJAPUR ROAD",
                "state": "",
                "arrival": "11:49",
                "departure": "11:50",
                "halt": 1,
                "day": 1,
                "distance": 116,
                "distanceFromSrc": 246
            },
            {
                "no": 12,
                "code": "ADVI",
                "station": "ADAVALI",
                "state": "",
                "arrival": "12:31",
                "departure": "12:32",
                "halt": 1,
                "day": 1,
                "distance": 175,
                "distanceFromSrc": 291
            },
            {
                "no": 13,
                "code": "RN",
                "station": "RATNAGIRI",
                "state": "",
                "arrival": "13:30",
                "departure": "13:35",
                "halt": 5,
                "day": 1,
                "distance": 160,
                "distanceFromSrc": 335
            },
            {
                "no": 14,
                "code": "SGR",
                "station": "SANGMESHWAR",
                "state": "",
                "arrival": "14:15",
                "departure": "14:16",
                "halt": 1,
                "day": 1,
                "distance": 222,
                "distanceFromSrc": 382
            },
            {
                "no": 15,
                "code": "CHI",
                "station": "CHIPLUN",
                "state": "",
                "arrival": "15:17",
                "departure": "15:18",
                "halt": 1,
                "day": 1,
                "distance": 219,
                "distanceFromSrc": 441
            },
            {
                "no": 16,
                "code": "KHED",
                "station": "KHED",
                "state": "",
                "arrival": "15:51",
                "departure": "15:52",
                "halt": 1,
                "day": 1,
                "distance": 263,
                "distanceFromSrc": 482
            },
            {
                "no": 17,
                "code": "MNI",
                "station": "MANGAON",
                "state": "",
                "arrival": "17:19",
                "departure": "17:20",
                "halt": 1,
                "day": 1,
                "distance": 315,
                "distanceFromSrc": 578
            },
            {
                "no": 18,
                "code": "PNVL",
                "station": "PANVEL",
                "state": "",
                "arrival": "19:25",
                "departure": "19:30",
                "halt": 5,
                "day": 1,
                "distance": 382,
                "distanceFromSrc": 697
            },
            {
                "no": 19,
                "code": "DIVA",
                "station": "DIVA",
                "state": "",
                "arrival": "20:01",
                "departure": "20:02",
                "halt": 1,
                "day": 1,
                "distance": 341,
                "distanceFromSrc": 723
            },
            {
                "no": 20,
                "code": "TNA",
                "station": "THANE",
                "state": "",
                "arrival": "20:38",
                "departure": "20:40",
                "halt": 2,
                "day": 1,
                "distance": 391,
                "distanceFromSrc": 732
            },
            {
                "no": 21,
                "code": "DR",
                "station": "DADAR",
                "state": "",
                "arrival": "21:02",
                "departure": "21:05",
                "halt": 3,
                "day": 1,
                "distance": 366,
                "distanceFromSrc": 757
            },
            {
                "no": 22,
                "code": "CSMT",
                "station": "Chhatrapati Shivaji Terminus MUMBAI CST",
                "state": "",
                "arrival": "21:40",
                "departure": "00:00",
                "halt": 0,
                "day": 1,
                "distance": 399,
                "distanceFromSrc": 765
            }
        ],
        "runtime": {
            "days": 0,
            "hours": 13,
            "mins": 40
        },
        "stops": 22,
        "avgSpeed": "46 km/hr",
        "seatsAvailibility": {
            "chaircar": {
                "charges_per_100km": 40,
                "total_coach": 10,
                "general_seats": 108,
                "ladies_seats": 0,
                "tatkal_seats": 0,
                "senior_citizen": 0
            },
            "firstAc": {
                "charges_per_100km": 295,
                "total_coach": 2,
                "general_seats": 6,
                "ladies_seats": 4,
                "tatkal_seats": 2,
                "senior_citizen": 6
            },
            "secondAc": {
                "charges_per_100km": 172,
                "total_coach": 2,
                "general_seats": 48,
                "ladies_seats": 4,
                "tatkal_seats": 4,
                "senior_citizen": 8
            },
            "thirdAc": {
                "charges_per_100km": 120,
                "total_coach": 4,
                "general_seats": 50,
                "ladies_seats": 4,
                "tatkal_seats": 9,
                "senior_citizen": 9
            },
            "sleeper": {
                "charges_per_100km": 46,
                "total_coach": 9,
                "general_seats": 50,
                "ladies_seats": 4,
                "tatkal_seats": 9,
                "senior_citizen": 9
            }
        },
        "classes": "2S SL 3A 2A 1A",
        "schedule": "S\tM\tT\tW\tT\tF\tS",
        "return": "10103"
    },
    {
        "_id": "63f9c31ec3f0a7c0f1c438eb",
        "trainno": "10215",
        "type": "",
        "train_name": "MADGAON ERS EXP",
        "distanceInKm": 850,
        "Route": [
            {
                "no": 1,
                "code": "MAO",
                "station": "MADGAON",
                "state": "",
                "arrival": "00:00",
                "departure": "21:00",
                "halt": 0,
                "day": 1,
                "distance": 0,
                "distanceFromSrc": 0
            },
            {
                "no": 2,
                "code": "KAWR",
                "station": "KARWAR",
                "state": "",
                "arrival": "22:00",
                "departure": "22:02",
                "halt": 2,
                "day": 1,
                "distance": 82,
                "distanceFromSrc": 82
            },
            {
                "no": 3,
                "code": "BTJL",
                "station": "BHATKAL",
                "state": "",
                "arrival": "00:06",
                "departure": "00:08",
                "halt": 2,
                "day": 2,
                "distance": 154,
                "distanceFromSrc": 236
            },
            {
                "no": 4,
                "code": "UD",
                "station": "UDUPI",
                "state": "",
                "arrival": "01:40",
                "departure": "01:42",
                "halt": 2,
                "day": 2,
                "distance": 196,
                "distanceFromSrc": 350
            },
            {
                "no": 5,
                "code": "TOK",
                "station": "THOKUR",
                "state": "",
                "arrival": "02:40",
                "departure": "02:45",
                "halt": 5,
                "day": 2,
                "distance": 219,
                "distanceFromSrc": 415
            },
            {
                "no": 6,
                "code": "MAJN",
                "station": "MANGALORE JN",
                "state": "",
                "arrival": "03:00",
                "departure": "03:10",
                "halt": 10,
                "day": 2,
                "distance": 212,
                "distanceFromSrc": 431
            },
            {
                "no": 7,
                "code": "KGQ",
                "station": "KASARAGOD",
                "state": "",
                "arrival": "03:53",
                "departure": "03:55",
                "halt": 2,
                "day": 2,
                "distance": 270,
                "distanceFromSrc": 482
            },
            {
                "no": 8,
                "code": "CAN",
                "station": "KANNUR",
                "state": "",
                "arrival": "05:10",
                "departure": "05:15",
                "halt": 5,
                "day": 2,
                "distance": 298,
                "distanceFromSrc": 568
            },
            {
                "no": 9,
                "code": "CLT",
                "station": "KOZHIKODE",
                "state": "",
                "arrival": "06:50",
                "departure": "06:55",
                "halt": 5,
                "day": 2,
                "distance": 359,
                "distanceFromSrc": 657
            },
            {
                "no": 10,
                "code": "TIR",
                "station": "TIRUR",
                "state": "",
                "arrival": "07:38",
                "departure": "07:40",
                "halt": 2,
                "day": 2,
                "distance": 339,
                "distanceFromSrc": 698
            },
            {
                "no": 11,
                "code": "SRR",
                "station": "SHORANUR JN",
                "state": "",
                "arrival": "08:35",
                "departure": "08:40",
                "halt": 5,
                "day": 2,
                "distance": 404,
                "distanceFromSrc": 743
            },
            {
                "no": 12,
                "code": "TCR",
                "station": "THRISUR",
                "state": "",
                "arrival": "09:18",
                "departure": "09:20",
                "halt": 2,
                "day": 2,
                "distance": 372,
                "distanceFromSrc": 776
            },
            {
                "no": 13,
                "code": "AWY",
                "station": "ALUVA",
                "state": "",
                "arrival": "10:38",
                "departure": "10:40",
                "halt": 2,
                "day": 2,
                "distance": 459,
                "distanceFromSrc": 831
            },
            {
                "no": 14,
                "code": "ERS",
                "station": "ERNAKULAM JN",
                "state": "",
                "arrival": "11:20",
                "departure": "00:00",
                "halt": 0,
                "day": 2,
                "distance": 391,
                "distanceFromSrc": 850
            }
        ],
        "runtime": {
            "days": 0,
            "hours": 14,
            "mins": 20
        },
        "stops": 14,
        "avgSpeed": "56 km/hr",
        "seatsAvailibility": {
            "firstAc": {
                "charges_per_100km": 295,
                "total_coach": 2,
                "general_seats": 6,
                "ladies_seats": 4,
                "tatkal_seats": 2,
                "senior_citizen": 6
            },
            "secondAc": {
                "charges_per_100km": 172,
                "total_coach": 2,
                "general_seats": 48,
                "ladies_seats": 4,
                "tatkal_seats": 4,
                "senior_citizen": 8
            },
            "thirdAc": {
                "charges_per_100km": 120,
                "total_coach": 4,
                "general_seats": 50,
                "ladies_seats": 4,
                "tatkal_seats": 9,
                "senior_citizen": 9
            },
            "sleeper": {
                "charges_per_100km": 46,
                "total_coach": 9,
                "general_seats": 50,
                "ladies_seats": 4,
                "tatkal_seats": 9,
                "senior_citizen": 9
            }
        },
        "classes": "SL 3A 2A 1A",
        "schedule": "S\t \t \t \t \t \t ",
        "return": "10216"
    },
    {
        "_id": "63f9c31ec3f0a7c0f1c438ec",
        "trainno": "10216",
        "type": "",
        "train_name": "MADGAON EXPRESS",
        "distanceInKm": 850,
        "Route": [
            {
                "no": 1,
                "code": "ERS",
                "station": "ERNAKULAM JN",
                "state": "",
                "arrival": "00:00",
                "departure": "13:55",
                "halt": 0,
                "day": 1,
                "distance": 0,
                "distanceFromSrc": 0
            },
            {
                "no": 2,
                "code": "AWY",
                "station": "ALUVA",
                "state": "",
                "arrival": "14:17",
                "departure": "14:19",
                "halt": 2,
                "day": 1,
                "distance": 20,
                "distanceFromSrc": 20
            },
            {
                "no": 3,
                "code": "TCR",
                "station": "THRISUR",
                "state": "",
                "arrival": "15:04",
                "departure": "15:07",
                "halt": 3,
                "day": 1,
                "distance": 55,
                "distanceFromSrc": 75
            },
            {
                "no": 4,
                "code": "SRR",
                "station": "SHORANUR JN",
                "state": "",
                "arrival": "16:00",
                "departure": "16:05",
                "halt": 5,
                "day": 1,
                "distance": 52,
                "distanceFromSrc": 107
            },
            {
                "no": 5,
                "code": "TIR",
                "station": "TIRUR",
                "state": "",
                "arrival": "16:43",
                "departure": "16:45",
                "halt": 2,
                "day": 1,
                "distance": 100,
                "distanceFromSrc": 152
            },
            {
                "no": 6,
                "code": "CLT",
                "station": "KOZHIKODE",
                "state": "",
                "arrival": "17:30",
                "departure": "17:35",
                "halt": 5,
                "day": 1,
                "distance": 93,
                "distanceFromSrc": 193
            },
            {
                "no": 7,
                "code": "CAN",
                "station": "KANNUR",
                "state": "",
                "arrival": "19:10",
                "departure": "19:15",
                "halt": 5,
                "day": 1,
                "distance": 190,
                "distanceFromSrc": 283
            },
            {
                "no": 8,
                "code": "KGQ",
                "station": "KASARAGOD",
                "state": "",
                "arrival": "20:08",
                "departure": "20:10",
                "halt": 2,
                "day": 1,
                "distance": 178,
                "distanceFromSrc": 368
            },
            {
                "no": 9,
                "code": "MAJN",
                "station": "MANGALORE JN",
                "state": "",
                "arrival": "21:20",
                "departure": "21:30",
                "halt": 10,
                "day": 1,
                "distance": 241,
                "distanceFromSrc": 419
            },
            {
                "no": 10,
                "code": "TOK",
                "station": "THOKUR",
                "state": "",
                "arrival": "21:40",
                "departure": "21:42",
                "halt": 2,
                "day": 1,
                "distance": 195,
                "distanceFromSrc": 436
            },
            {
                "no": 11,
                "code": "UD",
                "station": "UDUPI",
                "state": "",
                "arrival": "22:46",
                "departure": "22:48",
                "halt": 2,
                "day": 1,
                "distance": 306,
                "distanceFromSrc": 501
            },
            {
                "no": 12,
                "code": "BTJL",
                "station": "BHATKAL",
                "state": "",
                "arrival": "23:54",
                "departure": "23:56",
                "halt": 2,
                "day": 1,
                "distance": 308,
                "distanceFromSrc": 614
            },
            {
                "no": 13,
                "code": "KAWR",
                "station": "KARWAR",
                "state": "",
                "arrival": "02:02",
                "departure": "02:04",
                "halt": 2,
                "day": 2,
                "distance": 460,
                "distanceFromSrc": 768
            },
            {
                "no": 14,
                "code": "MAO",
                "station": "MADGAON",
                "state": "",
                "arrival": "03:30",
                "departure": "00:00",
                "halt": 0,
                "day": 2,
                "distance": 390,
                "distanceFromSrc": 850
            }
        ],
        "runtime": {
            "days": 0,
            "hours": 14,
            "mins": 30
        },
        "stops": 14,
        "avgSpeed": "53 km/hr",
        "seatsAvailibility": {
            "firstAc": {
                "charges_per_100km": 295,
                "total_coach": 2,
                "general_seats": 6,
                "ladies_seats": 4,
                "tatkal_seats": 2,
                "senior_citizen": 6
            },
            "secondAc": {
                "charges_per_100km": 172,
                "total_coach": 2,
                "general_seats": 48,
                "ladies_seats": 4,
                "tatkal_seats": 4,
                "senior_citizen": 8
            },
            "thirdAc": {
                "charges_per_100km": 120,
                "total_coach": 4,
                "general_seats": 50,
                "ladies_seats": 4,
                "tatkal_seats": 9,
                "senior_citizen": 9
            },
            "sleeper": {
                "charges_per_100km": 46,
                "total_coach": 9,
                "general_seats": 50,
                "ladies_seats": 4,
                "tatkal_seats": 9,
                "senior_citizen": 9
            }
        },
        "classes": "SL 3A 2A 1A",
        "schedule": " \tM\t \t \t \t \t ",
        "return": "10215"
    },
    {
        "_id": "63f9c31ec3f0a7c0f1c438ed",
        "trainno": "11003",
        "type": "",
        "train_name": "RAJYA RANI EXP",
        "distanceInKm": 647,
        "Route": [
            {
                "no": 1,
                "code": "DR",
                "station": "DADAR",
                "state": "",
                "arrival": "00:00",
                "departure": "00:05",
                "halt": 0,
                "day": 1,
                "distance": 0,
                "distanceFromSrc": 0
            },
            {
                "no": 2,
                "code": "TNA",
                "station": "THANE",
                "state": "",
                "arrival": "00:27",
                "departure": "00:30",
                "halt": 3,
                "day": 1,
                "distance": 25,
                "distanceFromSrc": 25
            },
            {
                "no": 3,
                "code": "DIVA",
                "station": "DIVA",
                "state": "",
                "arrival": "00:55",
                "departure": "00:56",
                "halt": 1,
                "day": 1,
                "distance": 9,
                "distanceFromSrc": 34
            },
            {
                "no": 4,
                "code": "PNVL",
                "station": "PANVEL",
                "state": "",
                "arrival": "01:15",
                "departure": "01:20",
                "halt": 5,
                "day": 1,
                "distance": 51,
                "distanceFromSrc": 60
            },
            {
                "no": 5,
                "code": "ROHA",
                "station": "ROHA",
                "state": "",
                "arrival": "03:15",
                "departure": "03:20",
                "halt": 5,
                "day": 1,
                "distance": 86,
                "distanceFromSrc": 137
            },
            {
                "no": 6,
                "code": "MNI",
                "station": "MANGAON",
                "state": "",
                "arrival": "03:46",
                "departure": "03:48",
                "halt": 2,
                "day": 1,
                "distance": 94,
                "distanceFromSrc": 180
            },
            {
                "no": 7,
                "code": "VEER",
                "station": "VEER",
                "state": "",
                "arrival": "04:02",
                "departure": "04:04",
                "halt": 2,
                "day": 1,
                "distance": 109,
                "distanceFromSrc": 203
            },
            {
                "no": 8,
                "code": "KHED",
                "station": "KHED",
                "state": "",
                "arrival": "05:02",
                "departure": "05:04",
                "halt": 2,
                "day": 1,
                "distance": 166,
                "distanceFromSrc": 275
            },
            {
                "no": 9,
                "code": "CHI",
                "station": "CHIPLUN",
                "state": "",
                "arrival": "05:34",
                "departure": "05:36",
                "halt": 2,
                "day": 1,
                "distance": 150,
                "distanceFromSrc": 316
            },
            {
                "no": 10,
                "code": "SVX",
                "station": "SAVARDA",
                "state": "",
                "arrival": "06:00",
                "departure": "06:02",
                "halt": 2,
                "day": 1,
                "distance": 192,
                "distanceFromSrc": 342
            },
            {
                "no": 11,
                "code": "AVRD",
                "station": "ARAVALI ROAD",
                "state": "",
                "arrival": "06:16",
                "departure": "06:18",
                "halt": 2,
                "day": 1,
                "distance": 164,
                "distanceFromSrc": 356
            },
            {
                "no": 12,
                "code": "SGR",
                "station": "SANGMESHWAR",
                "state": "",
                "arrival": "06:36",
                "departure": "06:38",
                "halt": 2,
                "day": 1,
                "distance": 212,
                "distanceFromSrc": 376
            },
            {
                "no": 13,
                "code": "RN",
                "station": "RATNAGIRI",
                "state": "",
                "arrival": "08:05",
                "departure": "08:10",
                "halt": 5,
                "day": 1,
                "distance": 210,
                "distanceFromSrc": 422
            },
            {
                "no": 14,
                "code": "ADVI",
                "station": "ADAVALI",
                "state": "",
                "arrival": "08:38",
                "departure": "08:40",
                "halt": 2,
                "day": 1,
                "distance": 257,
                "distanceFromSrc": 467
            },
            {
                "no": 15,
                "code": "VID",
                "station": "VILAVADE",
                "state": "",
                "arrival": "08:56",
                "departure": "08:58",
                "halt": 2,
                "day": 1,
                "distance": 231,
                "distanceFromSrc": 488
            },
            {
                "no": 16,
                "code": "RAJP",
                "station": "RAJAPUR ROAD",
                "state": "",
                "arrival": "09:10",
                "departure": "09:12",
                "halt": 2,
                "day": 1,
                "distance": 280,
                "distanceFromSrc": 511
            },
            {
                "no": 17,
                "code": "VBW",
                "station": "VAIBHAVWADI RD",
                "state": "",
                "arrival": "09:28",
                "departure": "09:30",
                "halt": 2,
                "day": 1,
                "distance": 255,
                "distanceFromSrc": 535
            },
            {
                "no": 18,
                "code": "NAN",
                "station": "NANDGAON ROAD",
                "state": "",
                "arrival": "09:48",
                "departure": "09:50",
                "halt": 2,
                "day": 1,
                "distance": 301,
                "distanceFromSrc": 556
            },
            {
                "no": 19,
                "code": "KKW",
                "station": "KANKAVALI",
                "state": "",
                "arrival": "10:18",
                "departure": "10:20",
                "halt": 2,
                "day": 1,
                "distance": 277,
                "distanceFromSrc": 578
            },
            {
                "no": 20,
                "code": "SNDD",
                "station": "SINDHUDURG",
                "state": "",
                "arrival": "10:38",
                "departure": "10:40",
                "halt": 2,
                "day": 1,
                "distance": 326,
                "distanceFromSrc": 603
            },
            {
                "no": 21,
                "code": "KUDL",
                "station": "KUDAL",
                "state": "",
                "arrival": "10:54",
                "departure": "10:56",
                "halt": 2,
                "day": 1,
                "distance": 291,
                "distanceFromSrc": 617
            },
            {
                "no": 22,
                "code": "SWV",
                "station": "SAWANTWADI ROAD",
                "state": "",
                "arrival": "12:10",
                "departure": "00:00",
                "halt": 0,
                "day": 1,
                "distance": 356,
                "distanceFromSrc": 647
            }
        ],
        "runtime": {
            "days": 0,
            "hours": 12,
            "mins": 10
        },
        "stops": 22,
        "avgSpeed": "47 km/hr",
        "seatsAvailibility": {
            "secondAc": {
                "charges_per_100km": 172,
                "total_coach": 2,
                "general_seats": 48,
                "ladies_seats": 4,
                "tatkal_seats": 4,
                "senior_citizen": 8
            },
            "thirdAc": {
                "charges_per_100km": 120,
                "total_coach": 4,
                "general_seats": 50,
                "ladies_seats": 4,
                "tatkal_seats": 9,
                "senior_citizen": 9
            },
            "sleeper": {
                "charges_per_100km": 46,
                "total_coach": 9,
                "general_seats": 50,
                "ladies_seats": 4,
                "tatkal_seats": 9,
                "senior_citizen": 9
            }
        },
        "classes": "SL 3A 2A",
        "schedule": "S\tM\tT\tW\tT\tF\tS",
        "return": "11004"
    },
    {
        "_id": "63f9c31ec3f0a7c0f1c438ee",
        "trainno": "11004",
        "type": "",
        "train_name": "RAJYA RANI EXP",
        "distanceInKm": 647,
        "Route": [
            {
                "no": 1,
                "code": "SWV",
                "station": "SAWANTWADI ROAD",
                "state": "",
                "arrival": "00:00",
                "departure": "17:30",
                "halt": 0,
                "day": 1,
                "distance": 0,
                "distanceFromSrc": 0
            },
            {
                "no": 2,
                "code": "KUDL",
                "station": "KUDAL",
                "state": "",
                "arrival": "17:52",
                "departure": "17:54",
                "halt": 2,
                "day": 1,
                "distance": 30,
                "distanceFromSrc": 30
            },
            {
                "no": 3,
                "code": "SNDD",
                "station": "SINDHUDURG",
                "state": "",
                "arrival": "18:06",
                "departure": "18:08",
                "halt": 2,
                "day": 1,
                "distance": 14,
                "distanceFromSrc": 44
            },
            {
                "no": 4,
                "code": "KKW",
                "station": "KANKAVALI",
                "state": "",
                "arrival": "18:26",
                "departure": "18:28",
                "halt": 2,
                "day": 1,
                "distance": 55,
                "distanceFromSrc": 69
            },
            {
                "no": 5,
                "code": "NAN",
                "station": "NANDGAON ROAD",
                "state": "",
                "arrival": "18:42",
                "departure": "18:44",
                "halt": 2,
                "day": 1,
                "distance": 36,
                "distanceFromSrc": 91
            },
            {
                "no": 6,
                "code": "VBW",
                "station": "VAIBHAVWADI RD",
                "state": "",
                "arrival": "19:00",
                "departure": "19:02",
                "halt": 2,
                "day": 1,
                "distance": 76,
                "distanceFromSrc": 112
            },
            {
                "no": 7,
                "code": "RAJP",
                "station": "RAJAPUR ROAD",
                "state": "",
                "arrival": "19:20",
                "departure": "19:22",
                "halt": 2,
                "day": 1,
                "distance": 60,
                "distanceFromSrc": 136
            },
            {
                "no": 8,
                "code": "VID",
                "station": "VILAVADE",
                "state": "",
                "arrival": "19:38",
                "departure": "19:40",
                "halt": 2,
                "day": 1,
                "distance": 99,
                "distanceFromSrc": 159
            },
            {
                "no": 9,
                "code": "ADVI",
                "station": "ADAVALI",
                "state": "",
                "arrival": "19:58",
                "departure": "20:00",
                "halt": 2,
                "day": 1,
                "distance": 82,
                "distanceFromSrc": 181
            },
            {
                "no": 10,
                "code": "RN",
                "station": "RATNAGIRI",
                "state": "",
                "arrival": "21:15",
                "departure": "21:20",
                "halt": 5,
                "day": 1,
                "distance": 143,
                "distanceFromSrc": 225
            },
            {
                "no": 11,
                "code": "SGR",
                "station": "SANGMESHWAR",
                "state": "",
                "arrival": "21:58",
                "departure": "22:00",
                "halt": 2,
                "day": 1,
                "distance": 129,
                "distanceFromSrc": 272
            },
            {
                "no": 12,
                "code": "AVRD",
                "station": "ARAVALI ROAD",
                "state": "",
                "arrival": "22:18",
                "departure": "22:20",
                "halt": 2,
                "day": 1,
                "distance": 162,
                "distanceFromSrc": 291
            },
            {
                "no": 13,
                "code": "SVX",
                "station": "SAVARDA",
                "state": "",
                "arrival": "22:34",
                "departure": "22:36",
                "halt": 2,
                "day": 1,
                "distance": 143,
                "distanceFromSrc": 305
            },
            {
                "no": 14,
                "code": "CHI",
                "station": "CHIPLUN",
                "state": "",
                "arrival": "22:54",
                "departure": "22:56",
                "halt": 2,
                "day": 1,
                "distance": 188,
                "distanceFromSrc": 331
            },
            {
                "no": 15,
                "code": "KHED",
                "station": "KHED",
                "state": "",
                "arrival": "23:50",
                "departure": "23:52",
                "halt": 2,
                "day": 1,
                "distance": 184,
                "distanceFromSrc": 372
            },
            {
                "no": 16,
                "code": "VEER",
                "station": "VEER",
                "state": "",
                "arrival": "01:18",
                "departure": "01:20",
                "halt": 2,
                "day": 2,
                "distance": 260,
                "distanceFromSrc": 444
            },
            {
                "no": 17,
                "code": "MNI",
                "station": "MANGAON",
                "state": "",
                "arrival": "01:48",
                "departure": "01:50",
                "halt": 2,
                "day": 2,
                "distance": 208,
                "distanceFromSrc": 468
            },
            {
                "no": 18,
                "code": "ROHA",
                "station": "ROHA",
                "state": "",
                "arrival": "03:15",
                "departure": "03:20",
                "halt": 5,
                "day": 2,
                "distance": 302,
                "distanceFromSrc": 510
            },
            {
                "no": 19,
                "code": "PNVL",
                "station": "PANVEL",
                "state": "",
                "arrival": "04:45",
                "departure": "04:50",
                "halt": 5,
                "day": 2,
                "distance": 285,
                "distanceFromSrc": 587
            },
            {
                "no": 20,
                "code": "DIVA",
                "station": "DIVA",
                "state": "",
                "arrival": "05:01",
                "departure": "05:02",
                "halt": 1,
                "day": 2,
                "distance": 328,
                "distanceFromSrc": 613
            },
            {
                "no": 21,
                "code": "TNA",
                "station": "THANE",
                "state": "",
                "arrival": "05:43",
                "departure": "05:45",
                "halt": 2,
                "day": 2,
                "distance": 294,
                "distanceFromSrc": 622
            },
            {
                "no": 22,
                "code": "DR",
                "station": "DADAR",
                "state": "",
                "arrival": "06:45",
                "departure": "00:00",
                "halt": 0,
                "day": 2,
                "distance": 353,
                "distanceFromSrc": 647
            }
        ],
        "runtime": {
            "days": 0,
            "hours": 13,
            "mins": 45
        },
        "stops": 22,
        "avgSpeed": "43 km/hr",
        "seatsAvailibility": {
            "secondAc": {
                "charges_per_100km": 172,
                "total_coach": 2,
                "general_seats": 48,
                "ladies_seats": 4,
                "tatkal_seats": 4,
                "senior_citizen": 8
            },
            "thirdAc": {
                "charges_per_100km": 120,
                "total_coach": 4,
                "general_seats": 50,
                "ladies_seats": 4,
                "tatkal_seats": 9,
                "senior_citizen": 9
            },
            "sleeper": {
                "charges_per_100km": 46,
                "total_coach": 9,
                "general_seats": 50,
                "ladies_seats": 4,
                "tatkal_seats": 9,
                "senior_citizen": 9
            }
        },
        "classes": "SL 3A 2A",
        "schedule": "S\tM\tT\tW\tT\tF\tS",
        "return": "11003"
    },
    {
        "_id": "63f9c31ec3f0a7c0f1c438ef",
        "trainno": "11005",
        "type": "",
        "train_name": "PUDUCHERRY EXP",
        "distanceInKm": 1643,
        "Route": [
            {
                "no": 1,
                "code": "DR",
                "station": "DADAR",
                "state": "",
                "arrival": "00:00",
                "departure": "21:30",
                "halt": 0,
                "day": 1,
                "distance": 0,
                "distanceFromSrc": 0
            },
            {
                "no": 2,
                "code": "KYN",
                "station": "KALYAN JN",
                "state": "",
                "arrival": "22:06",
                "departure": "22:10",
                "halt": 4,
                "day": 1,
                "distance": 45,
                "distanceFromSrc": 45
            },
            {
                "no": 3,
                "code": "KJT",
                "station": "KARJAT",
                "state": "",
                "arrival": "22:53",
                "departure": "22:55",
                "halt": 2,
                "day": 1,
                "distance": 46,
                "distanceFromSrc": 91
            },
            {
                "no": 4,
                "code": "LNL",
                "station": "LONAVALA",
                "state": "",
                "arrival": "23:43",
                "departure": "23:45",
                "halt": 2,
                "day": 1,
                "distance": 73,
                "distanceFromSrc": 119
            },
            {
                "no": 5,
                "code": "PUNE",
                "station": "PUNE JN",
                "state": "",
                "arrival": "01:00",
                "departure": "01:10",
                "halt": 10,
                "day": 2,
                "distance": 110,
                "distanceFromSrc": 183
            },
            {
                "no": 6,
                "code": "STR",
                "station": "SATARA",
                "state": "",
                "arrival": "03:57",
                "departure": "04:00",
                "halt": 3,
                "day": 2,
                "distance": 218,
                "distanceFromSrc": 328
            },
            {
                "no": 7,
                "code": "KRD",
                "station": "KARAD",
                "state": "",
                "arrival": "04:52",
                "departure": "04:55",
                "halt": 3,
                "day": 2,
                "distance": 169,
                "distanceFromSrc": 387
            },
            {
                "no": 8,
                "code": "TKR",
                "station": "TAKARI",
                "state": "",
                "arrival": "05:18",
                "departure": "05:20",
                "halt": 2,
                "day": 2,
                "distance": 245,
                "distanceFromSrc": 414
            },
            {
                "no": 9,
                "code": "SLI",
                "station": "SANGLI",
                "state": "",
                "arrival": "06:12",
                "departure": "06:15",
                "halt": 3,
                "day": 2,
                "distance": 210,
                "distanceFromSrc": 455
            },
            {
                "no": 10,
                "code": "MRJ",
                "station": "MIRAJ JN",
                "state": "",
                "arrival": "06:50",
                "departure": "06:55",
                "halt": 5,
                "day": 2,
                "distance": 252,
                "distanceFromSrc": 462
            },
            {
                "no": 11,
                "code": "KUD",
                "station": "KUDACHI",
                "state": "",
                "arrival": "07:23",
                "departure": "07:25",
                "halt": 2,
                "day": 2,
                "distance": 243,
                "distanceFromSrc": 495
            },
            {
                "no": 12,
                "code": "GPB",
                "station": "GHATPRABHA",
                "state": "",
                "arrival": "08:00",
                "departure": "08:02",
                "halt": 2,
                "day": 2,
                "distance": 299,
                "distanceFromSrc": 542
            },
            {
                "no": 13,
                "code": "BGM",
                "station": "BELGAUM",
                "state": "",
                "arrival": "09:03",
                "departure": "09:05",
                "halt": 2,
                "day": 2,
                "distance": 301,
                "distanceFromSrc": 600
            },
            {
                "no": 14,
                "code": "LD",
                "station": "LONDA JN",
                "state": "",
                "arrival": "09:58",
                "departure": "10:00",
                "halt": 2,
                "day": 2,
                "distance": 350,
                "distanceFromSrc": 651
            },
            {
                "no": 15,
                "code": "LWR",
                "station": "ALNAVAR JN",
                "state": "",
                "arrival": "10:38",
                "departure": "10:40",
                "halt": 2,
                "day": 2,
                "distance": 334,
                "distanceFromSrc": 684
            },
            {
                "no": 16,
                "code": "DWR",
                "station": "DHARWAR",
                "state": "",
                "arrival": "11:25",
                "departure": "11:27",
                "halt": 2,
                "day": 2,
                "distance": 387,
                "distanceFromSrc": 721
            },
            {
                "no": 17,
                "code": "UBL",
                "station": "HUBLI JN",
                "state": "",
                "arrival": "12:30",
                "departure": "12:40",
                "halt": 10,
                "day": 2,
                "distance": 354,
                "distanceFromSrc": 741
            },
            {
                "no": 18,
                "code": "HVR",
                "station": "HAVERI",
                "state": "",
                "arrival": "13:43",
                "departure": "13:45",
                "halt": 2,
                "day": 2,
                "distance": 462,
                "distanceFromSrc": 816
            },
            {
                "no": 19,
                "code": "RNR",
                "station": "RANIBENNUR",
                "state": "",
                "arrival": "14:13",
                "departure": "14:15",
                "halt": 2,
                "day": 2,
                "distance": 387,
                "distanceFromSrc": 849
            },
            {
                "no": 20,
                "code": "HRR",
                "station": "HARIHAR",
                "state": "",
                "arrival": "14:43",
                "departure": "14:45",
                "halt": 2,
                "day": 2,
                "distance": 484,
                "distanceFromSrc": 871
            },
            {
                "no": 21,
                "code": "DVG",
                "station": "DAVANGERE",
                "state": "",
                "arrival": "14:57",
                "departure": "15:00",
                "halt": 3,
                "day": 2,
                "distance": 401,
                "distanceFromSrc": 885
            },
            {
                "no": 22,
                "code": "RRB",
                "station": "BIRUR JN",
                "state": "",
                "arrival": "17:03",
                "departure": "17:05",
                "halt": 2,
                "day": 2,
                "distance": 598,
                "distanceFromSrc": 999
            },
            {
                "no": 23,
                "code": "DRU",
                "station": "KADUR",
                "state": "",
                "arrival": "17:15",
                "departure": "17:17",
                "halt": 2,
                "day": 2,
                "distance": 407,
                "distanceFromSrc": 1005
            },
            {
                "no": 24,
                "code": "ASK",
                "station": "ARSIKERE JN",
                "state": "",
                "arrival": "18:05",
                "departure": "18:10",
                "halt": 5,
                "day": 2,
                "distance": 638,
                "distanceFromSrc": 1045
            },
            {
                "no": 25,
                "code": "TTR",
                "station": "TIPTUR",
                "state": "",
                "arrival": "18:36",
                "departure": "18:38",
                "halt": 2,
                "day": 2,
                "distance": 432,
                "distanceFromSrc": 1070
            },
            {
                "no": 26,
                "code": "TK",
                "station": "TUMKUR",
                "state": "",
                "arrival": "19:28",
                "departure": "19:30",
                "halt": 2,
                "day": 2,
                "distance": 709,
                "distanceFromSrc": 1141
            },
            {
                "no": 27,
                "code": "YPR",
                "station": "YESVANTPUR JN",
                "state": "",
                "arrival": "21:30",
                "departure": "22:00",
                "halt": 30,
                "day": 2,
                "distance": 496,
                "distanceFromSrc": 1205
            },
            {
                "no": 28,
                "code": "BAND",
                "station": "BANASWADI",
                "state": "",
                "arrival": "22:19",
                "departure": "22:21",
                "halt": 2,
                "day": 2,
                "distance": 723,
                "distanceFromSrc": 1219
            },
            {
                "no": 29,
                "code": "KJM",
                "station": "KRISHNARAJAPURM",
                "state": "",
                "arrival": "22:33",
                "departure": "22:35",
                "halt": 2,
                "day": 2,
                "distance": 504,
                "distanceFromSrc": 1227
            },
            {
                "no": 30,
                "code": "BWT",
                "station": "BANGARAPET",
                "state": "",
                "arrival": "23:25",
                "departure": "23:27",
                "halt": 2,
                "day": 2,
                "distance": 779,
                "distanceFromSrc": 1283
            },
            {
                "no": 31,
                "code": "JTJ",
                "station": "JOLARPETTAI",
                "state": "",
                "arrival": "01:08",
                "departure": "01:10",
                "halt": 2,
                "day": 3,
                "distance": 582,
                "distanceFromSrc": 1361
            },
            {
                "no": 32,
                "code": "KPD",
                "station": "KATPADI JN",
                "state": "",
                "arrival": "02:30",
                "departure": "02:50",
                "halt": 20,
                "day": 3,
                "distance": 863,
                "distanceFromSrc": 1445
            },
            {
                "no": 33,
                "code": "VLR",
                "station": "VELLORE CANT",
                "state": "",
                "arrival": "03:03",
                "departure": "03:05",
                "halt": 2,
                "day": 3,
                "distance": 592,
                "distanceFromSrc": 1455
            },
            {
                "no": 34,
                "code": "ARV",
                "station": "ARNI ROAD",
                "state": "",
                "arrival": "03:23",
                "departure": "03:25",
                "halt": 2,
                "day": 3,
                "distance": 898,
                "distanceFromSrc": 1490
            },
            {
                "no": 35,
                "code": "PRL",
                "station": "POLUR",
                "state": "",
                "arrival": "03:38",
                "departure": "03:40",
                "halt": 2,
                "day": 3,
                "distance": 609,
                "distanceFromSrc": 1507
            },
            {
                "no": 36,
                "code": "TNM",
                "station": "TIRUVANNAMALAI",
                "state": "",
                "arrival": "04:28",
                "departure": "04:30",
                "halt": 2,
                "day": 3,
                "distance": 929,
                "distanceFromSrc": 1538
            },
            {
                "no": 37,
                "code": "TRK",
                "station": "TIRUKOILUR",
                "state": "",
                "arrival": "04:53",
                "departure": "04:55",
                "halt": 2,
                "day": 3,
                "distance": 643,
                "distanceFromSrc": 1572
            },
            {
                "no": 38,
                "code": "VM",
                "station": "VILLUPURAM JN",
                "state": "",
                "arrival": "06:20",
                "departure": "06:25",
                "halt": 5,
                "day": 3,
                "distance": 962,
                "distanceFromSrc": 1605
            },
            {
                "no": 39,
                "code": "PDY",
                "station": "PUDUCHERRY",
                "state": "",
                "arrival": "07:50",
                "departure": "00:00",
                "halt": 0,
                "day": 3,
                "distance": 681,
                "distanceFromSrc": 1643
            }
        ],
        "runtime": {
            "days": 1,
            "hours": 10,
            "mins": 50
        },
        "stops": 39,
        "avgSpeed": "49 km/hr",
        "seatsAvailibility": {
            "secondAc": {
                "charges_per_100km": 172,
                "total_coach": 2,
                "general_seats": 48,
                "ladies_seats": 4,
                "tatkal_seats": 4,
                "senior_citizen": 8
            },
            "thirdAc": {
                "charges_per_100km": 120,
                "total_coach": 4,
                "general_seats": 50,
                "ladies_seats": 4,
                "tatkal_seats": 9,
                "senior_citizen": 9
            },
            "sleeper": {
                "charges_per_100km": 46,
                "total_coach": 9,
                "general_seats": 50,
                "ladies_seats": 4,
                "tatkal_seats": 9,
                "senior_citizen": 9
            }
        },
        "classes": "SL 3A 2A",
        "schedule": "S\tM\t \t \t \tF\t ",
        "return": "11006"
    },
    {
        "_id": "63f9c31ec3f0a7c0f1c438f0",
        "trainno": "11006",
        "type": "",
        "train_name": "CHALUKYA  EXP",
        "distanceInKm": 1643,
        "Route": [
            {
                "no": 1,
                "code": "PDY",
                "station": "PUDUCHERRY",
                "state": "",
                "arrival": "00:00",
                "departure": "20:30",
                "halt": 0,
                "day": 1,
                "distance": 0,
                "distanceFromSrc": 0
            },
            {
                "no": 2,
                "code": "VM",
                "station": "VILLUPURAM JN",
                "state": "",
                "arrival": "21:10",
                "departure": "21:15",
                "halt": 5,
                "day": 1,
                "distance": 38,
                "distanceFromSrc": 38
            },
            {
                "no": 3,
                "code": "TRK",
                "station": "TIRUKOILUR",
                "state": "",
                "arrival": "21:44",
                "departure": "21:45",
                "halt": 1,
                "day": 1,
                "distance": 34,
                "distanceFromSrc": 72
            },
            {
                "no": 4,
                "code": "TNM",
                "station": "TIRUVANNAMALAI",
                "state": "",
                "arrival": "22:34",
                "departure": "22:35",
                "halt": 1,
                "day": 1,
                "distance": 72,
                "distanceFromSrc": 106
            },
            {
                "no": 5,
                "code": "PRL",
                "station": "POLUR",
                "state": "",
                "arrival": "22:54",
                "departure": "22:55",
                "halt": 1,
                "day": 1,
                "distance": 65,
                "distanceFromSrc": 137
            },
            {
                "no": 6,
                "code": "ARV",
                "station": "ARNI ROAD",
                "state": "",
                "arrival": "23:09",
                "departure": "23:10",
                "halt": 1,
                "day": 1,
                "distance": 88,
                "distanceFromSrc": 153
            },
            {
                "no": 7,
                "code": "VLR",
                "station": "VELLORE CANT",
                "state": "",
                "arrival": "23:54",
                "departure": "23:55",
                "halt": 1,
                "day": 1,
                "distance": 100,
                "distanceFromSrc": 188
            },
            {
                "no": 8,
                "code": "KPD",
                "station": "KATPADI JN",
                "state": "",
                "arrival": "01:05",
                "departure": "01:25",
                "halt": 20,
                "day": 2,
                "distance": 98,
                "distanceFromSrc": 198
            },
            {
                "no": 9,
                "code": "JTJ",
                "station": "JOLARPETTAI",
                "state": "",
                "arrival": "02:43",
                "departure": "02:45",
                "halt": 2,
                "day": 2,
                "distance": 184,
                "distanceFromSrc": 282
            },
            {
                "no": 10,
                "code": "BWT",
                "station": "BANGARAPET",
                "state": "",
                "arrival": "03:48",
                "departure": "03:50",
                "halt": 2,
                "day": 2,
                "distance": 176,
                "distanceFromSrc": 360
            },
            {
                "no": 11,
                "code": "KJM",
                "station": "KRISHNARAJAPURM",
                "state": "",
                "arrival": "04:43",
                "departure": "04:45",
                "halt": 2,
                "day": 2,
                "distance": 240,
                "distanceFromSrc": 416
            },
            {
                "no": 12,
                "code": "BAND",
                "station": "BANASWADI",
                "state": "",
                "arrival": "05:13",
                "departure": "05:15",
                "halt": 2,
                "day": 2,
                "distance": 184,
                "distanceFromSrc": 424
            },
            {
                "no": 13,
                "code": "YPR",
                "station": "YESVANTPUR JN",
                "state": "",
                "arrival": "06:00",
                "departure": "07:00",
                "halt": 60,
                "day": 2,
                "distance": 255,
                "distanceFromSrc": 439
            },
            {
                "no": 14,
                "code": "TK",
                "station": "TUMKUR",
                "state": "",
                "arrival": "08:03",
                "departure": "08:05",
                "halt": 2,
                "day": 2,
                "distance": 248,
                "distanceFromSrc": 503
            },
            {
                "no": 15,
                "code": "TTR",
                "station": "TIPTUR",
                "state": "",
                "arrival": "09:08",
                "departure": "09:10",
                "halt": 2,
                "day": 2,
                "distance": 325,
                "distanceFromSrc": 573
            },
            {
                "no": 16,
                "code": "ASK",
                "station": "ARSIKERE JN",
                "state": "",
                "arrival": "09:40",
                "departure": "09:45",
                "halt": 5,
                "day": 2,
                "distance": 274,
                "distanceFromSrc": 599
            },
            {
                "no": 17,
                "code": "DRU",
                "station": "KADUR",
                "state": "",
                "arrival": "10:23",
                "departure": "10:25",
                "halt": 2,
                "day": 2,
                "distance": 364,
                "distanceFromSrc": 638
            },
            {
                "no": 18,
                "code": "RRB",
                "station": "BIRUR JN",
                "state": "",
                "arrival": "10:33",
                "departure": "10:35",
                "halt": 2,
                "day": 2,
                "distance": 280,
                "distanceFromSrc": 644
            },
            {
                "no": 19,
                "code": "DVG",
                "station": "DAVANGERE",
                "state": "",
                "arrival": "12:13",
                "departure": "12:15",
                "halt": 2,
                "day": 2,
                "distance": 479,
                "distanceFromSrc": 759
            },
            {
                "no": 20,
                "code": "HRR",
                "station": "HARIHAR",
                "state": "",
                "arrival": "12:33",
                "departure": "12:35",
                "halt": 2,
                "day": 2,
                "distance": 293,
                "distanceFromSrc": 772
            },
            {
                "no": 21,
                "code": "RNR",
                "station": "RANIBENNUR",
                "state": "",
                "arrival": "12:58",
                "departure": "13:00",
                "halt": 2,
                "day": 2,
                "distance": 502,
                "distanceFromSrc": 795
            },
            {
                "no": 22,
                "code": "HVR",
                "station": "HAVERI",
                "state": "",
                "arrival": "13:28",
                "departure": "13:30",
                "halt": 2,
                "day": 2,
                "distance": 325,
                "distanceFromSrc": 827
            },
            {
                "no": 23,
                "code": "UBL",
                "station": "HUBLI JN",
                "state": "",
                "arrival": "15:10",
                "departure": "15:25",
                "halt": 15,
                "day": 2,
                "distance": 577,
                "distanceFromSrc": 902
            },
            {
                "no": 24,
                "code": "DWR",
                "station": "DHARWAR",
                "state": "",
                "arrival": "15:48",
                "departure": "15:50",
                "halt": 2,
                "day": 2,
                "distance": 345,
                "distanceFromSrc": 922
            },
            {
                "no": 25,
                "code": "LWR",
                "station": "ALNAVAR JN",
                "state": "",
                "arrival": "16:29",
                "departure": "16:30",
                "halt": 1,
                "day": 2,
                "distance": 614,
                "distanceFromSrc": 959
            },
            {
                "no": 26,
                "code": "LD",
                "station": "LONDA JN",
                "state": "",
                "arrival": "17:08",
                "departure": "17:10",
                "halt": 2,
                "day": 2,
                "distance": 379,
                "distanceFromSrc": 993
            },
            {
                "no": 27,
                "code": "BGM",
                "station": "BELGAUM",
                "state": "",
                "arrival": "18:03",
                "departure": "18:05",
                "halt": 2,
                "day": 2,
                "distance": 665,
                "distanceFromSrc": 1044
            },
            {
                "no": 28,
                "code": "GPB",
                "station": "GHATPRABHA",
                "state": "",
                "arrival": "18:54",
                "departure": "18:55",
                "halt": 1,
                "day": 2,
                "distance": 437,
                "distanceFromSrc": 1102
            },
            {
                "no": 29,
                "code": "KUD",
                "station": "KUDACHI",
                "state": "",
                "arrival": "19:39",
                "departure": "19:40",
                "halt": 1,
                "day": 2,
                "distance": 711,
                "distanceFromSrc": 1148
            },
            {
                "no": 30,
                "code": "MRJ",
                "station": "MIRAJ JN",
                "state": "",
                "arrival": "20:45",
                "departure": "20:50",
                "halt": 5,
                "day": 2,
                "distance": 470,
                "distanceFromSrc": 1181
            },
            {
                "no": 31,
                "code": "SLI",
                "station": "SANGLI",
                "state": "",
                "arrival": "21:02",
                "departure": "21:05",
                "halt": 3,
                "day": 2,
                "distance": 718,
                "distanceFromSrc": 1188
            },
            {
                "no": 32,
                "code": "TKR",
                "station": "TAKARI",
                "state": "",
                "arrival": "21:39",
                "departure": "21:40",
                "halt": 1,
                "day": 2,
                "distance": 512,
                "distanceFromSrc": 1230
            },
            {
                "no": 33,
                "code": "KRD",
                "station": "KARAD",
                "state": "",
                "arrival": "22:07",
                "departure": "22:08",
                "halt": 1,
                "day": 2,
                "distance": 744,
                "distanceFromSrc": 1256
            },
            {
                "no": 34,
                "code": "STR",
                "station": "SATARA",
                "state": "",
                "arrival": "23:05",
                "departure": "23:08",
                "halt": 3,
                "day": 2,
                "distance": 571,
                "distanceFromSrc": 1315
            },
            {
                "no": 35,
                "code": "PUNE",
                "station": "PUNE JN",
                "state": "",
                "arrival": "02:10",
                "departure": "02:20",
                "halt": 10,
                "day": 3,
                "distance": 889,
                "distanceFromSrc": 1460
            },
            {
                "no": 36,
                "code": "LNL",
                "station": "LONAVALA",
                "state": "",
                "arrival": "03:24",
                "departure": "03:25",
                "halt": 1,
                "day": 3,
                "distance": 635,
                "distanceFromSrc": 1524
            },
            {
                "no": 37,
                "code": "KYN",
                "station": "KALYAN JN",
                "state": "",
                "arrival": "04:47",
                "departure": "04:50",
                "halt": 3,
                "day": 3,
                "distance": 963,
                "distanceFromSrc": 1598
            },
            {
                "no": 38,
                "code": "DR",
                "station": "DADAR",
                "state": "",
                "arrival": "05:45",
                "departure": "00:00",
                "halt": 0,
                "day": 3,
                "distance": 680,
                "distanceFromSrc": 1643
            }
        ],
        "runtime": {
            "days": 1,
            "hours": 8,
            "mins": 45
        },
        "stops": 38,
        "avgSpeed": "51 km/hr",
        "seatsAvailibility": {
            "secondAc": {
                "charges_per_100km": 172,
                "total_coach": 2,
                "general_seats": 48,
                "ladies_seats": 4,
                "tatkal_seats": 4,
                "senior_citizen": 8
            },
            "thirdAc": {
                "charges_per_100km": 120,
                "total_coach": 4,
                "general_seats": 50,
                "ladies_seats": 4,
                "tatkal_seats": 9,
                "senior_citizen": 9
            },
            "sleeper": {
                "charges_per_100km": 46,
                "total_coach": 9,
                "general_seats": 50,
                "ladies_seats": 4,
                "tatkal_seats": 9,
                "senior_citizen": 9
            }
        },
        "classes": "SL 3A 2A",
        "schedule": "S\t \tT\tW\t \t \t ",
        "return": "11005"
    },
    {
        "_id": "63f9c31ec3f0a7c0f1c438f1",
        "trainno": "11007",
        "type": "",
        "train_name": "DECCAN EXPRESS",
        "distanceInKm": 192,
        "Route": [
            {
                "no": 1,
                "code": "CSMT",
                "station": "Chhatrapati Shivaji Terminus MUMBAI CST",
                "state": "",
                "arrival": "00:00",
                "departure": "07:00",
                "halt": 0,
                "day": 1,
                "distance": 0,
                "distanceFromSrc": 0
            },
            {
                "no": 2,
                "code": "DR",
                "station": "DADAR",
                "state": "",
                "arrival": "07:11",
                "departure": "07:13",
                "halt": 2,
                "day": 1,
                "distance": 9,
                "distanceFromSrc": 9
            },
            {
                "no": 3,
                "code": "TNA",
                "station": "THANE",
                "state": "",
                "arrival": "07:33",
                "departure": "07:35",
                "halt": 2,
                "day": 1,
                "distance": 25,
                "distanceFromSrc": 34
            },
            {
                "no": 4,
                "code": "KYN",
                "station": "KALYAN JN",
                "state": "",
                "arrival": "07:53",
                "departure": "07:55",
                "halt": 2,
                "day": 1,
                "distance": 29,
                "distanceFromSrc": 54
            },
            {
                "no": 5,
                "code": "NRL",
                "station": "NERAL",
                "state": "",
                "arrival": "08:25",
                "departure": "08:27",
                "halt": 2,
                "day": 1,
                "distance": 58,
                "distanceFromSrc": 87
            },
            {
                "no": 6,
                "code": "KJT",
                "station": "KARJAT",
                "state": "",
                "arrival": "08:43",
                "departure": "08:45",
                "halt": 2,
                "day": 1,
                "distance": 42,
                "distanceFromSrc": 100
            },
            {
                "no": 7,
                "code": "KAD",
                "station": "KHANDALA",
                "state": "",
                "arrival": "09:28",
                "departure": "09:30",
                "halt": 2,
                "day": 1,
                "distance": 82,
                "distanceFromSrc": 124
            },
            {
                "no": 8,
                "code": "LNL",
                "station": "LONAVALA",
                "state": "",
                "arrival": "09:38",
                "departure": "09:40",
                "halt": 2,
                "day": 1,
                "distance": 46,
                "distanceFromSrc": 128
            },
            {
                "no": 9,
                "code": "TGN",
                "station": "TALEGAON",
                "state": "",
                "arrival": "10:08",
                "departure": "10:10",
                "halt": 2,
                "day": 1,
                "distance": 112,
                "distanceFromSrc": 158
            },
            {
                "no": 10,
                "code": "KK",
                "station": "KHADKI",
                "state": "",
                "arrival": "10:44",
                "departure": "10:46",
                "halt": 2,
                "day": 1,
                "distance": 74,
                "distanceFromSrc": 186
            },
            {
                "no": 11,
                "code": "SVJR",
                "station": "SHIVAJINAGAR",
                "state": "",
                "arrival": "10:49",
                "departure": "10:51",
                "halt": 2,
                "day": 1,
                "distance": 116,
                "distanceFromSrc": 190
            },
            {
                "no": 12,
                "code": "PUNE",
                "station": "PUNE JN",
                "state": "",
                "arrival": "11:05",
                "departure": "00:00",
                "halt": 0,
                "day": 1,
                "distance": 76,
                "distanceFromSrc": 192
            }
        ],
        "runtime": {
            "days": 0,
            "hours": 4,
            "mins": 5
        },
        "stops": 12,
        "avgSpeed": "47 km/hr",
        "seatsAvailibility": {
            "chaircar": {
                "charges_per_100km": 40,
                "total_coach": 10,
                "general_seats": 108,
                "ladies_seats": 0,
                "tatkal_seats": 0,
                "senior_citizen": 0
            },
            "accar": {
                "charges_per_100km": 235,
                "total_coach": 8,
                "general_seats": 78,
                "ladies_seats": 0,
                "tatkal_seats": 0,
                "senior_citizen": 0
            }
        },
        "classes": "2S CC EV",
        "schedule": "S\tM\tT\tW\tT\tF\tS",
        "return": "11008"
    },
    {
        "_id": "63f9c31ec3f0a7c0f1c438f2",
        "trainno": "11008",
        "type": "",
        "train_name": "DECCAN EXPRESS",
        "distanceInKm": 192,
        "Route": [
            {
                "no": 1,
                "code": "PUNE",
                "station": "PUNE JN",
                "state": "",
                "arrival": "00:00",
                "departure": "15:30",
                "halt": 0,
                "day": 1,
                "distance": 0,
                "distanceFromSrc": 0
            },
            {
                "no": 2,
                "code": "SVJR",
                "station": "SHIVAJINAGAR",
                "state": "",
                "arrival": "15:35",
                "departure": "15:38",
                "halt": 3,
                "day": 1,
                "distance": 3,
                "distanceFromSrc": 3
            },
            {
                "no": 3,
                "code": "KK",
                "station": "KHADKI",
                "state": "",
                "arrival": "15:42",
                "departure": "15:45",
                "halt": 3,
                "day": 1,
                "distance": 4,
                "distanceFromSrc": 7
            },
            {
                "no": 4,
                "code": "TGN",
                "station": "TALEGAON",
                "state": "",
                "arrival": "16:06",
                "departure": "16:08",
                "halt": 2,
                "day": 1,
                "distance": 31,
                "distanceFromSrc": 35
            },
            {
                "no": 5,
                "code": "LNL",
                "station": "LONAVALA",
                "state": "",
                "arrival": "16:38",
                "departure": "16:40",
                "halt": 2,
                "day": 1,
                "distance": 33,
                "distanceFromSrc": 64
            },
            {
                "no": 6,
                "code": "KAD",
                "station": "KHANDALA",
                "state": "",
                "arrival": "16:43",
                "departure": "16:45",
                "halt": 2,
                "day": 1,
                "distance": 35,
                "distanceFromSrc": 68
            },
            {
                "no": 7,
                "code": "KJT",
                "station": "KARJAT",
                "state": "",
                "arrival": "17:33",
                "departure": "17:35",
                "halt": 2,
                "day": 1,
                "distance": 57,
                "distanceFromSrc": 92
            },
            {
                "no": 8,
                "code": "KYN",
                "station": "KALYAN JN",
                "state": "",
                "arrival": "18:18",
                "departure": "18:23",
                "halt": 5,
                "day": 1,
                "distance": 82,
                "distanceFromSrc": 139
            },
            {
                "no": 9,
                "code": "TNA",
                "station": "THANE",
                "state": "",
                "arrival": "18:43",
                "departure": "18:45",
                "halt": 2,
                "day": 1,
                "distance": 77,
                "distanceFromSrc": 159
            },
            {
                "no": 10,
                "code": "DR",
                "station": "DADAR",
                "state": "",
                "arrival": "19:08",
                "departure": "19:10",
                "halt": 2,
                "day": 1,
                "distance": 106,
                "distanceFromSrc": 183
            },
            {
                "no": 11,
                "code": "CSMT",
                "station": "Chhatrapati Shivaji Terminus MUMBAI CST",
                "state": "",
                "arrival": "19:35",
                "departure": "00:00",
                "halt": 0,
                "day": 1,
                "distance": 86,
                "distanceFromSrc": 192
            }
        ],
        "runtime": {
            "days": 0,
            "hours": 4,
            "mins": 35
        },
        "stops": 11,
        "avgSpeed": "50 km/hr",
        "seatsAvailibility": {
            "chaircar": {
                "charges_per_100km": 40,
                "total_coach": 10,
                "general_seats": 108,
                "ladies_seats": 0,
                "tatkal_seats": 0,
                "senior_citizen": 0
            },
            "accar": {
                "charges_per_100km": 235,
                "total_coach": 8,
                "general_seats": 78,
                "ladies_seats": 0,
                "tatkal_seats": 0,
                "senior_citizen": 0
            }
        },
        "classes": "2S CC EV",
        "schedule": "S\tM\tT\tW\tT\tF\tS",
        "return": "11007"
    }
];
const fs = require("fs")

const dst = "HWH", src = "DURE";

const len = sampleData.length;

sampleData.forEach(element => {
    let dstInd = -1, srcInd = -1;
    element.Route.every(e => {
        if (element.Route[len - 1].code === src) {
            return false;
        }
        if (dstInd !== -1 && srcInd !== -1) {
            return false;
        }
        if (e.code === dst) {
            dstInd = e.no;
        }
        if (e.code === src) {
            srcInd = e.no;
        }
        if (element.Route[len - 1].code === dst) {
            dstInd = len;
        }
        return true;
    })
    if (dstInd > srcInd) {
        sampleData.push(element);
    }
});

fs.writeFileSync('data.json', JSON.stringify(sampleData.slice(len)), () => {
    console.log("data saved");
})

let timeTaken = Date.now() - start;
console.log("Total time taken : " + timeTaken + " milliseconds");